import { StyleSheet } from "react-native";

const AddReportStyles = StyleSheet.create({
  fullScreenContainer: {
    flex: 1,
    paddingHorizontal: 15,
    paddingTop: 20,
    paddingBottom: 140,
  },
  heading: {
    fontSize: 24,
    fontWeight: "700",
    color: "white",
    marginBottom: 20,
    letterSpacing: 1,
  },
  headerContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
    justifyContent: "center",
    position: "relative",
  },
  input: {
    backgroundColor: "#f3f4f6",
    borderColor: "#cbd5e1",
    borderWidth: 1,
    borderRadius: 8,
    paddingVertical: 14,
    paddingHorizontal: 18,
    fontSize: 16,
    marginBottom: 18,
    color: "#1e293b",
    fontWeight: "500",
  },
  dateInput: {
    backgroundColor: "#f3f4f6",
    borderColor: "#cbd5e1",
    borderWidth: 1,
    borderRadius: 8,
    paddingVertical: 14,
    paddingHorizontal: 18,
    marginBottom: 18,
  },
  dateText: {
    fontSize: 16,
    color: "#1e293b",
    fontWeight: "500",
  },
  dropdown: {
    backgroundColor: "#f3f4f6",
    borderColor: "#cbd5e1",
    borderWidth: 1,
    borderRadius: 8,
    paddingVertical: 14,
    paddingHorizontal: 18,
    marginBottom: 18,
  },
  dropdownText: {
    fontSize: 16,
    color: "#475569",
  },
  dropdownList: {
    backgroundColor: "#ffffff",
    borderRadius: 8,
    borderColor: "#cbd5e1",
    borderWidth: 1,
    maxHeight: 300,
    marginBottom: 18,
    paddingVertical: 6,
  },
  dropdownItem: {
    paddingVertical: 12,
    paddingHorizontal: 18,
  },
  tagText: {
    fontSize: 16,
    color: "#334155",
  },
  tagSelected: {
    fontWeight: "700",
    color: "#2563eb",
  },
  selectedTagsContainer: {
    flexDirection: "row",
    marginBottom: 8,
  },
  selectedTag: {
    flexDirection: "row",
    backgroundColor: "#2563eb",
    borderRadius: 16,
    paddingVertical: 4,
    paddingHorizontal: 12,
    marginRight: 8,
    alignItems: "center",
  },
  selectedTagText: {
    color: "white",
    fontWeight: "600",
    marginRight: 6,
  },
  removeTagButton: {
    backgroundColor: "#ef4444",
    borderRadius: 12,
    width: 20,
    height: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  removeTagButtonText: {
    color: "#fff",
    fontSize: 14,
    lineHeight: 14,
    fontWeight: "bold",
  },
  searchInput: {
    backgroundColor: "#f3f4f6",
    borderColor: "#cbd5e1",
    borderWidth: 1,
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
    fontSize: 16,
    marginBottom: 8,
    color: "#1e293b",
  },
  searchInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f3f4f6",
    borderColor: "#cbd5e1",
    borderWidth: 1,
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginBottom: 8,
  },
  searchInputWithClose: {
    flex: 1,
    fontSize: 16,
    color: "#1e293b",
  },
  closeButton: {
    marginLeft: 8,
    backgroundColor: "#ef4444",
    borderRadius: 12,
    width: 28,
    height: 28,
    justifyContent: "center",
    alignItems: "center",
  },
  closeButtonText: {
    color: "#fff",
    fontSize: 20,
    lineHeight: 20,
    fontWeight: "bold",
  },
  mediaPreviewContainer: {
    flexDirection: "row",
    marginBottom: 16,
  },
  mediaThumbnail: {
    width: 140,
    height: 140,
    borderRadius: 10,
    marginRight: 12,
  },
  mediaFileContainer: {
    width: 140,
    height: 140,
    borderRadius: 10,
    backgroundColor: "#e2e8f0",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
    paddingHorizontal: 8,
    position: "relative",
  },
  mediaFileName: {
    fontSize: 14,
    color: "#475569",
    maxWidth: "80%",
    textAlign: "center",
  },
  imageWrapper: {
    position: "relative",
    marginRight: 12,
  },
  removeButton: {
    position: "absolute",
    top: 4,
    right: 4,
    backgroundColor: "#ef4444",
    borderRadius: 14,
    width: 28,
    height: 28,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 10,
  },
  removeButtonAudio: {
    position: "absolute",
    top: 4,
    right: 4,
    backgroundColor: "#ef4444",
    borderRadius: 14,
    width: 28,
    height: 28,
    justifyContent: "center",
    alignItems: "center",
  },
  removeButtonText: {
    color: "#fff",
    fontSize: 20,
    lineHeight: 20,
    fontWeight: "bold",
  },
  videoThumbnail: {
    width: 140,
    height: 140,
    borderRadius: 10,
    marginRight: 12,
    backgroundColor: "#000",
  },
  playButton: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: [{ translateX: -20 }, { translateY: -20 }],
    zIndex: 5,
  },
  button: {
    backgroundColor: "#2563eb",
    borderRadius: 10,
    paddingVertical: 16,
    marginTop: 12,
    marginBottom: 12,
    alignItems: "center",
    shadowColor: "#2563eb",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 8,
  },
  buttonClose: {
    marginTop: 4,
  },
  buttonDisabled: {
    backgroundColor: "#93c5fd",
    shadowOpacity: 0.2,
  },
  buttonText: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "700",
  },
  progressText: {
    textAlign: "center",
    marginTop: 10,
    color: "#64748b",
    fontSize: 15,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.3)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: "#ffffff",
    padding: 28,
    borderRadius: 16,
    alignItems: "center",
    width: "85%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 12,
  },
  modalText: {
    fontSize: 18,
    color: "#334155",
    marginBottom: 20,
    textAlign: "center",
    fontWeight: "600",
  },
  draftSavedText: {
    textAlign: "center",
    color: "#64748b",
    fontSize: 14,
    marginTop: 8,
    marginBottom: 16,
    fontStyle: "italic",
  },
  backButton: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
    position: "absolute",
    left: 0,
  },
  backButtonText: {
    color: "white",
    fontSize: 16,
    marginLeft: 6,
    fontWeight: "600",
  },
});

export default AddReportStyles;
